before_script:
  - echo -e "Host *\n\tStrictHostKeyChecking no\n" >> ~/.ssh/config
  - whoami

language: node_js
node_js:
  - "0.10.26"
notifications:
  email:
    - jw@slickage.com
    - ed@slickage.com
    - julie@slickage.com
    - anthony@slickage.com
    - warren@slickage.com

